package Logica;


public enum InteracaoEsperada {

    INTERACAO_WAIT_BEGINNING, INTERACAO_WAIT_SHIP_SELECTION, INTERACAO_WAIT_MOVE,
    INTERACAO_WAIT_EVENT, INTERACAO_WAIT_PLANET_SECTOR, INTERACAO_WAIT_LANDING,
    INTERACAO_WAIT_SPACE_STATION, INTERACAO_WAIT_GAMEOVER
    
}
